service: serverless-nodejs-api

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1
  environment:
    STAGE: ${opt:stage}

functions:
  getMsg:
    handler: index.api
    events:
      - http: GET /